### ISSUE TITLE
只能压缩单张图片，不能压缩整个文件夹的图片

### ISSUE THREAD

**Issue by allenlzg** [nieyuyao/tinypng#1]

**Comment by allenlzg** [comment]
files = _files.filter((file: any) => {
    console.log(file)
    return imgReg.test(file.name||file);
  });
tasks = files.map((filename: any) => {
    filename = filename.name || filename;



}

这两个地方 加上 判断 就可以了

**Comment by nieyuyao** [comment]
> files = _files.filter((file: any) => {
> console.log(file)
> return imgReg.test(file.name||file);
> });
> tasks = files.map((filename: any) => {
> filename = filename.name || filename;
> 
> }
> 
> 这两个地方 加上 判断 就可以了

直接执行 `tinypngs`命令就可以压缩整个文件夹下的问价了

**Comment by nieyuyao** [comment]
> files = _files.filter((file: any) => {
> console.log(file)
> return imgReg.test(file.name||file);
> });
> tasks = files.map((filename: any) => {
> filename = filename.name || filename;
> 
> }
> 
> 这两个地方 加上 判断 就可以了

直接执行`tinypngs`命令就可以压缩整个文件夹下的文件了
